---
# tasks/main.yml for node-exporter role

- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes

- name: Start and enable Node Exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Wait for Node Exporter to be ready
  wait_for:
    host: localhost
    port: 9100
    timeout: 10

- name: Include validation tasks
  include_tasks: validate.yml
  tags:
    - validate
    - always
