---
# tasks/validate.yml for node-exporter role

- name: Check if Node Exporter service is running
  systemd:
    name: prometheus-node-exporter
    state: started
  register: node_exporter_service_status

- name: Assert Node Exporter service is running
  assert:
    that: node_exporter_service_status.state == 'started'
    success_msg: "✅ Node Exporter service is running"
    fail_msg: "❌ Node Exporter service is not running"

- name: Check Node Exporter metrics endpoint
  uri:
    url: http://localhost:9100/metrics
    method: GET
    status_code: 200
  register: node_exporter_metrics_check
  ignore_errors: yes

- name: Assert Node Exporter metrics endpoint is accessible
  assert:
    that: node_exporter_metrics_check.status == 200
    success_msg: "✅ Node Exporter metrics endpoint is responding"
    fail_msg: "❌ Node Exporter metrics endpoint is not accessible"

- name: Check Node Exporter package is installed
  package_facts:
    manager: apt
  register: package_facts

- name: Assert Node Exporter package is installed
  assert:
    that: "'prometheus-node-exporter' in ansible_facts.packages"
    success_msg: "✅ Node Exporter package is installed"
    fail_msg: "❌ Node Exporter package is not installed"
