---
# handlers file for network role

- name: Validate netplan configuration (generate only)
  listen: Apply netplan config
  ansible.builtin.command: netplan generate
  register: netplan_generate
  changed_when: false
  failed_when: netplan_generate.rc != 0
  become: yes

- name: Apply netplan asynchronously (non-blocking)
  listen: Apply netplan config
  ansible.builtin.command: netplan apply
  async: 45
  poll: 0
  become: yes
  when: not ansible_check_mode

- name: Verify IPv4 routing after netplan apply
  listen: Apply netplan config
  ansible.builtin.command: ip -4 route get 8.8.8.8
  register: post_route_check
  changed_when: false
  failed_when: false
  become: yes
  when: not ansible_check_mode
