---
# tasks/validate.yml for influxdb role

- name: Check if InfluxDB service is running
  systemd:
    name: influxdb
    state: started
  register: influxdb_service_status

- name: Assert InfluxDB service is running
  assert:
    that: influxdb_service_status.state == 'started'
    success_msg: "✅ InfluxDB service is running"
    fail_msg: "❌ InfluxDB service is not running"

- name: Check InfluxDB HTTP endpoint
  uri:
    url: http://localhost:8086/health
    method: GET
    status_code: 200
  register: influxdb_health_check
  ignore_errors: yes

- name: Assert InfluxDB HTTP endpoint is accessible
  assert:
    that: influxdb_health_check.status == 200
    success_msg: "✅ InfluxDB HTTP endpoint is responding"
    fail_msg: "❌ InfluxDB HTTP endpoint is not accessible"

- name: Check InfluxDB package is installed
  package_facts:
    manager: apt
  register: package_facts

- name: Assert InfluxDB package is installed
  assert:
    that: "'influxdb2' in ansible_facts.packages"
    success_msg: "✅ InfluxDB package is installed"
    fail_msg: "❌ InfluxDB package is not installed"
