---
# tasks/main.yml for cockpit role

- name: Check if backports repository already exists
  stat:
    path: /etc/apt/sources.list.d/backports.list
  register: backports_repo_exists

- name: Add Debian Bookworm backports repository
  apt_repository:
    repo: 'deb http://deb.debian.org/debian bookworm-backports main'
    filename: backports
    state: present
    update_cache: yes
  when: not backports_repo_exists.stat.exists

- name: Update apt cache to ensure repository is available
  apt:
    update_cache: yes
  when: not backports_repo_exists.stat.exists

- name: Install Cockpit from backports
  apt:
    name: 'cockpit'
    state: present
    update_cache: yes
  notify: restart cockpit

- name: Enable and start Cockpit service
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Allow Cockpit through UFW
  ufw:
    rule: allow
    port: '9090'
    proto: tcp

- name: Include validation tasks
  include_tasks: validate.yml
  tags:
    - validate
    - always
