---
# tasks/main.yml for cockpit role

- name: Check if backports repository already exists
  stat:
    path: /etc/apt/sources.list.d/backports.list
  register: backports_repo_exists

- name: Add Debian Bookworm backports repository
  apt_repository:
    repo: 'deb http://deb.debian.org/debian bookworm-backports main'
    filename: backports
    state: present
    update_cache: yes
  when: not backports_repo_exists.stat.exists

- name: Update apt cache to ensure repository is available
  apt:
    update_cache: yes
  when: not backports_repo_exists.stat.exists

- name: Install Cockpit from backports
  apt:
    name: 'cockpit'
    state: present
    update_cache: yes
  notify: restart cockpit

- name: Create cockpit socket directory for overrides
  file:
    path: /etc/systemd/system/cockpit.socket.d
    state: directory
    mode: '0755'
  when: not ansible_check_mode

- name: Configure Cockpit socket to listen on custom port
  template:
    src: socket.override.conf.j2
    dest: /etc/systemd/system/cockpit.socket.d/port.conf
    mode: '0644'
  when: not ansible_check_mode
  notify: restart cockpit socket

- name: Stop existing cockpit service (port conflict resolution)
  systemd:
    name: cockpit.socket
    state: stopped
    enabled: no
  when: not ansible_check_mode
  ignore_errors: yes

- name: Reload systemd daemon (for cockpit socket override)
  systemd:
    daemon_reload: yes
  when: not ansible_check_mode

- name: Enable and start Cockpit service on new port
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
  when: not ansible_check_mode

- name: Check if Cockpit service would be enabled and started (check mode)
  debug:
    msg: "Cockpit service would be enabled and started"
  when: ansible_check_mode

- name: Allow Cockpit through UFW on new port
  ufw:
    rule: allow
    port: '{{ cockpit_port }}'
    proto: tcp
  when: not ansible_check_mode

- name: Check if Cockpit would be allowed through UFW (check mode)
  debug:
    msg: "Cockpit would be allowed through UFW on port {{ cockpit_port }}"
  when: ansible_check_mode

- name: Include validation tasks
  include_tasks: validate.yml
  tags:
    - validate
    - always
