---
# Monitor Server Setup - Simplified Single-Playbook Deployment
# This playbook configures the complete monitor server stack
#
# Prerequisites: Run ./setup_network.sh on the server first
#
# Usage: ansible-playbook -i inventory.ini site.yml

- name: Monitor Server Setup
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Display provisioning start message
      debug:
        msg: "Starting Monitor Server provisioning for {{ ansible_hostname }} ({{ ansible_host }})"
      tags: [always]

  roles:
    - basic-utilities
    - cockpit
    - nginx-proxy
    - website

  post_tasks:
    - name: Display deployment summary
      debug:
        msg: |
          === Monitor Server Deployment Complete ===
          Server: {{ ansible_hostname }}
          IP: {{ ansible_host }}
          Cockpit UI: https://{{ ansible_host }}:9090
          Web Dashboard: https://{{ ansible_host }}
          SSH: ssh monitor@{{ ansible_host }}

    - name: Validate core services
      include_tasks: roles/basic-utilities/tasks/validate.yml
      tags: [validate]

    - name: Validate basic connectivity
      command: echo "Server is reachable and configured"
      register: connectivity_check
      changed_when: false
      failed_when: connectivity_check.rc != 0
      tags: [validate]

    - name: Validate Cockpit installation
      include_tasks: roles/cockpit/tasks/validate.yml
      tags: [validate]

    - name: Validate Nginx proxy
      include_tasks: roles/nginx-proxy/tasks/validate.yml
      tags: [validate]

    - name: Validate website deployment
      include_tasks: roles/website/tasks/validate.yml
      tags: [validate]

    - name: Final connectivity test
      uri:
        url: "https://{{ ansible_host }}"
        validate_certs: no
        return_content: yes
        status_code: 200
      register: final_web_test
      failed_when: false
      ignore_errors: yes
      when: not ansible_check_mode
      tags: [validate]

    - name: Final success message
      debug:
        msg: "🎉 All services deployed and validated successfully!"
      when: final_web_test is defined and final_web_test.status == 200
