---
# tasks/validate.yml for snmp-exporter role

- name: Check if SNMP Exporter service is running
  systemd:
    name: prometheus-snmp-exporter
    state: started
  register: snmp_exporter_service_status

- name: Assert SNMP Exporter service is running
  assert:
    that: snmp_exporter_service_status.state == 'started'
    success_msg: "✅ SNMP Exporter service is running"
    fail_msg: "❌ SNMP Exporter service is not running"

- name: Check SNMP Exporter metrics endpoint
  uri:
    url: http://localhost:9116/metrics
    method: GET
    status_code: 200
  register: snmp_exporter_metrics_check
  ignore_errors: yes

- name: Assert SNMP Exporter metrics endpoint is accessible
  assert:
    that: snmp_exporter_metrics_check.status == 200
    success_msg: "✅ SNMP Exporter metrics endpoint is responding"
    fail_msg: "❌ SNMP Exporter metrics endpoint is not accessible"

- name: Check SNMP Exporter package is installed
  package_facts:
    manager: apt
  register: package_facts

- name: Assert SNMP Exporter package is installed
  assert:
    that: "'prometheus-snmp-exporter' in ansible_facts.packages"
    success_msg: "✅ SNMP Exporter package is installed"
    fail_msg: "❌ SNMP Exporter package is not installed"
