---
# tasks/main.yml for ssh-hardening role

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes
  # Install UFW from stable repositories to manage firewall rules

- name: Deploy hardened SSH configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: Restart SSH service
  # Deploy a custom SSH configuration with enhanced security settings

- name: Ensure SSH service is enabled and running
  service:
    name: ssh
    state: started
    enabled: yes
  # Ensure SSH service is active and starts on boot
