---
# tasks/validate.yml for website-deploy role

- name: Check if index.html exists
  stat:
    path: /usr/share/nginx/html/index.html
  register: index_file_stat

- name: Assert index.html exists
  assert:
    that: index_file_stat.stat.exists
    success_msg: "✅ index.html landing page exists"
    fail_msg: "❌ index.html landing page not found"

- name: Check if devices.html exists
  stat:
    path: /usr/share/nginx/html/devices.html
  register: devices_file_stat

- name: Assert devices.html exists
  assert:
    that: devices_file_stat.stat.exists
    success_msg: "✅ devices.html page exists"
    fail_msg: "❌ devices.html page not found"

- name: Check if Bootstrap CSS exists
  stat:
    path: /usr/share/nginx/html/css/bootstrap.min.css
  register: css_file_stat

- name: Assert Bootstrap CSS exists
  assert:
    that: css_file_stat.stat.exists
    success_msg: "✅ Bootstrap CSS files exist"
    fail_msg: "❌ Bootstrap CSS files not found"

- name: Check if Bootstrap JS exists
  stat:
    path: /usr/share/nginx/html/js/bootstrap.bundle.min.js
  register: js_file_stat

- name: Assert Bootstrap JS exists
  assert:
    that: js_file_stat.stat.exists
    success_msg: "✅ Bootstrap JS files exist"
    fail_msg: "❌ Bootstrap JS files not found"
