---
# tasks file for basic-utilities role

- name: Install essential packages
  apt:
    name:
      - curl        # Essential for HTTP/API requests and downloading files
      - iputils-ping  # Network connectivity testing and troubleshooting
      - net-tools   # Classic networking utilities (netstat, ifconfig, route)
      - apt-transport-https  # Secure repository access via HTTPS
      - ca-certificates  # SSL/TLS certificate validation for secure connections
    state: present  # Ensures idempotency - package will be installed if not present
    update_cache: yes  # Updates the package cache before installation
    cache_valid_time: 3600  # Cache is considered valid for 1 hour (3600 seconds)
  become: yes  # Use sudo to perform this task
  # No additional sources.list modifications - using default Debian stable repositories

# Note: No handlers are required as no services are being started or restarted

- name: Include validation tasks
  include_tasks: validate.yml
  tags: validate
