---
# Validation tasks for basic-utilities role
# These tasks verify that all essential packages are properly installed

- name: Validate curl installation
  command: dpkg -l curl
  register: curl_check
  failed_when: curl_check.rc != 0
  changed_when: false  # Read-only operation, never reports changed
  tags: validate

- name: Display curl validation result
  debug:
    msg: "curl package is installed and available"
  when: curl_check.rc == 0
  tags: validate

- name: Validate iputils-ping installation
  command: dpkg -l iputils-ping
  register: ping_check
  failed_when: ping_check.rc != 0
  changed_when: false
  tags: validate

- name: Display iputils-ping validation result
  debug:
    msg: "iputils-ping package is installed and available"
  when: ping_check.rc == 0
  tags: validate

- name: Validate net-tools installation
  command: dpkg -l net-tools
  register: nettools_check
  failed_when: nettools_check.rc != 0
  changed_when: false
  tags: validate

- name: Display net-tools validation result
  debug:
    msg: "net-tools package is installed and available"
  when: nettools_check.rc == 0
  tags: validate

- name: Validate apt-transport-https installation
  command: dpkg -l apt-transport-https
  register: https_transport_check
  failed_when: https_transport_check.rc != 0
  changed_when: false
  tags: validate

- name: Display apt-transport-https validation result
  debug:
    msg: "apt-transport-https package is installed and available"
  when: https_transport_check.rc == 0
  tags: validate

- name: Validate ca-certificates installation
  command: dpkg -l ca-certificates
  register: ca_certs_check
  failed_when: ca_certs_check.rc != 0
  changed_when: false
  tags: validate

- name: Display ca-certificates validation result
  debug:
    msg: "ca-certificates package is installed and available"
  when: ca_certs_check.rc == 0
  tags: validate

- name: Functional test - Verify curl can make HTTPS requests
  command: curl -s --head https://httpbin.org/get
  register: curl_https_test
  failed_when: curl_https_test.rc != 0
  changed_when: false
  tags: validate

- name: Display curl HTTPS functionality result
  debug:
    msg: "curl can successfully make HTTPS requests"
  when: curl_https_test.rc == 0
  tags: validate

- name: Functional test - Verify ping functionality
  command: ping -c 1 8.8.8.8
  register: ping_test
  failed_when: ping_test.rc != 0
  changed_when: false
  tags: validate

- name: Display ping functionality result
  debug:
    msg: "ping functionality is working correctly"
  when: ping_test.rc == 0
  tags: validate

- name: Display validation summary
  debug:
    msg: "All basic utilities have been validated successfully!"
  tags: validate
