---
# tasks/main.yml for prometheus role

- name: Install Prometheus
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Configure Prometheus main config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0640'
    validate: 'promtool check config %s'
  notify: restart_prometheus

- name: Create Prometheus web config for basic auth
  template:
    src: web.yml.j2
    dest: /etc/prometheus/web.yml
    owner: prometheus
    group: prometheus
    mode: '0640'

- name: Ensure Prometheus service override directory exists
  file:
    path: /etc/systemd/system/prometheus.service.d
    state: directory
    mode: '0755'

- name: Configure Prometheus startup overrides
  template:
    src: prometheus-override.conf.j2
    dest: /etc/systemd/system/prometheus.service.d/override.conf
    mode: '0644'
  notify: restart_prometheus

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: stopped
    enabled: no

- name: Wait briefly for service to stop
  pause:
    seconds: 2

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Prometheus to be ready
  wait_for:
    host: localhost
    port: 9090
    timeout: 60

- name: Include validation tasks
  include_tasks: validate.yml
  tags:
    - validate
    - always
