---
# tasks/validate.yml for prometheus role

- name: Check if Prometheus service is running
  systemd:
    name: prometheus
    state: started
  register: prometheus_service_status

- name: Assert Prometheus service is running
  assert:
    that: prometheus_service_status.state == 'started'
    success_msg: "✅ Prometheus service is running"
    fail_msg: "❌ Prometheus service is not running"

- name: Check Prometheus HTTP endpoint
  uri:
    url: http://localhost:9090/-/healthy
    method: GET
    status_code: 200
  register: prometheus_health_check
  ignore_errors: yes

- name: Assert Prometheus HTTP endpoint is accessible
  assert:
    that: prometheus_health_check.status == 200
    success_msg: "✅ Prometheus HTTP endpoint is responding"
    fail_msg: "❌ Prometheus HTTP endpoint is not accessible"

- name: Check Prometheus config syntax
  command: promtool check config /etc/prometheus/prometheus.yml
  register: config_check
  failed_when: false

- name: Assert Prometheus configuration is valid
  assert:
    that: config_check.rc == 0
    success_msg: "✅ Prometheus configuration is valid"
    fail_msg: "❌ Prometheus configuration is invalid: {{ config_check.stderr }}"

- name: Check Prometheus package is installed
  package_facts:
    manager: apt
  register: package_facts

- name: Assert Prometheus package is installed
  assert:
    that: "'prometheus' in ansible_facts.packages"
    success_msg: "✅ Prometheus package is installed"
    fail_msg: "❌ Prometheus package is not installed"
