---
# meta/main.yml for nginx-proxy role
galaxy_info:
  author: NetAuto Team
  description: Nginx reverse proxy configuration for NetAuto Server
  company: Ready-1
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - nginx
    - proxy
    - ssl

dependencies: []
