---
# tasks/validate.yml for blackbox-exporter role

- name: Check if Blackbox Exporter service is running
  systemd:
    name: prometheus-blackbox-exporter
    state: started
  register: blackbox_exporter_service_status

- name: Assert Blackbox Exporter service is running
  assert:
    that: blackbox_exporter_service_status.state == 'started'
    success_msg: "✅ Blackbox Exporter service is running"
    fail_msg: "❌ Blackbox Exporter service is not running"

- name: Check Blackbox Exporter metrics endpoint
  uri:
    url: http://localhost:9115/metrics
    method: GET
    status_code: 200
  register: blackbox_exporter_metrics_check
  ignore_errors: yes

- name: Assert Blackbox Exporter metrics endpoint is accessible
  assert:
    that: blackbox_exporter_metrics_check.status == 200
    success_msg: "✅ Blackbox Exporter metrics endpoint is responding"
    fail_msg: "❌ Blackbox Exporter metrics endpoint is not accessible"

- name: Check Blackbox Exporter package is installed
  package_facts:
    manager: apt
  register: package_facts

- name: Assert Blackbox Exporter package is installed
  assert:
    that: "'prometheus-blackbox-exporter' in ansible_facts.packages"
    success_msg: "✅ Blackbox Exporter package is installed"
    fail_msg: "❌ Blackbox Exporter package is not installed"
