---
# tasks file for initial_setup role

- name: Create user with sudo privileges
  user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes
  become: yes
  register: user_created

- name: Ensure .ssh directory exists with correct permissions
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Deploy SSH public key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_monitor_ed25519.pub') }}"
    state: present
  become: yes
  notify: Restart SSH service

- name: Include validation tasks
  include_tasks: validate.yml
  tags: validate
